"""Versioned instruction suffixes used by the Terminal-Bench adapter."""

BENCHMARK_PROMPTS = {
    "none": "",
    "verify-v1": (
        "Before finishing, verify the final state against every requirement "
        "with direct checks. For services and configuration, exercise the "
        "changed behavior end to end rather than relying only on a syntax "
        "check. When restoring existing files or commits, use version-control "
        "operations instead of reconstructing content so exact bytes are "
        "preserved. Prefer the smallest direct solution, stop exploration once "
        "the acceptance criteria pass, and do not report success while any "
        "check fails."
    ),
    "verify-v2": (
        "Before finishing, verify the final state against every requirement "
        "with direct checks. For services and configuration, exercise the "
        "changed behavior end to end rather than relying only on a syntax "
        "check. Treat data created only for verification as disposable: after "
        "the checks pass, restore the intended pre-client state and confirm it "
        "is ready for fresh evaluator input. Keep the requested infrastructure "
        "and configuration running, but do not leave verification-only branches, "
        "commits, records, jobs, processes, or content unless the task explicitly "
        "requires that seed state. When restoring existing files or commits, use "
        "version-control operations instead of reconstructing content so exact "
        "bytes are preserved. Prefer the smallest direct solution, stop exploration "
        "once the acceptance criteria pass, and do not report success while any "
        "check fails."
    ),
    "verify-v3": (
        "Before finishing, verify the final state against every requirement "
        "with direct checks. For services and configuration, exercise the "
        "changed behavior end to end rather than relying only on a syntax "
        "check. Treat requirements about future client actions—such as pushes, "
        "writes, requests, or jobs—as future-facing. If the task does not name "
        "exact initial client data that must remain, leave the corresponding "
        "client state empty and ready for fresh evaluator input. Any data created "
        "to exercise the behavior is a disposable verification fixture, not seed "
        "state: remove its branches, commits, records, jobs, processes, files, and "
        "deployed content after checking. Keep requested infrastructure and "
        "configuration running. When restoring existing files or commits, use "
        "version-control operations instead of reconstructing content so exact "
        "bytes are preserved. Prefer the smallest direct solution, stop exploration "
        "once the acceptance criteria pass, and do not report success while any "
        "check fails."
    ),
    "verify-v4": (
        "Before finishing, verify the final state against every requirement "
        "with direct checks. For services and configuration, exercise the "
        "changed behavior end to end rather than relying only on a syntax "
        "check. Test existing behavior from the client boundary before replacing "
        "an installed service's configuration or starting a parallel daemon. A "
        "policy-denied or unreadable config path is unavailable evidence, not "
        "evidence that the service is misconfigured; reuse the distribution "
        "service when its effective behavior passes. Keep verification commands "
        "individually time-bounded and non-interactive. Do not clear the harness's "
        "prompt-control environment with `env -i` unless all required prompt, "
        "credential, PATH, HOME, and connection-timeout settings are supplied "
        "again. Treat requirements about future client actions—such as pushes, "
        "writes, requests, or jobs—as future-facing. If the task does not name "
        "exact initial client data that must remain, leave the corresponding "
        "client state empty and ready for fresh evaluator input. Any data created "
        "to exercise the behavior is a disposable verification fixture, not seed "
        "state: remove its branches, commits, records, jobs, processes, files, and "
        "deployed content after checking. Keep requested infrastructure and "
        "configuration running. When restoring existing files or commits, use "
        "version-control operations instead of reconstructing content so exact "
        "bytes are preserved. Prefer the smallest direct solution, stop exploration "
        "once the acceptance criteria pass, and do not report success while any "
        "check fails."
    ),
}

DEFAULT_BENCHMARK_PROMPT = "verify-v4"
